apiVersion: v1
kind: Pod
metadata:
  name: duckdb
spec:
  containers:
    - name: duckdb
      image: duckdb/duckdb:1.5.3
      command: ["duckdb"]
      stdin: true
      tty: true
  restartPolicy: Never
